sudo: required

services:
  - docker

before_install:
  - docker pull marceldiass/statuspage

script:
  - docker run --rm -t marceldiass/statuspage update --name=StatusTest --token=$GH_TOKEN

branches:
  only:
  - master
  - gh-pages
